spring.application.name=PAS_XCONTROL_PAS_WMS
server.port=3030
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.boot.admin.client.url=http://localhost:8080
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin123
management.endpoint.logfile.access=read_only
logging.file.path=logs
logging.file.name=C:/logs/PAS_WMS_SERVICE/wms-xcontrol-service.log
management.server.port=6262
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.prometheus.access=read_only
management.metrics.tags.application=${spring.application.name}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.compression.enabled=true
spring.jpa.hibernate.ddl-auto=validate
# =========================
# XControl Api
# =========================
xcontrol.base.url:http://212.56.45.62:36594/colorada_api/api/xcontrol/
xcontrol.auth:Basic Y3Bzd2ViYXBwOndlYmFwcDEyMzox
# =========================
# AUTH DB
# =========================
spring.datasource.auth.jdbc-url=${JDBC_AUTH}
spring.datasource.auth.username=${DM_DB_USER}
spring.datasource.auth.password=${DM_DB_PASS}
spring.datasource.auth.driver-class-name=org.postgresql.Driver
# =========================
# WMS DB
# =========================
spring.datasource.wms.jdbc-url=${JDBC_WMS}
spring.datasource.wms.username=${DM_DB_USER}
spring.datasource.wms.password=${DM_DB_PASS}
spring.datasource.wms.driver-class-name=org.postgresql.Driver
# =========================
# COMMUNICATION SERVICE
# =========================
server.communication=http://localhost:6063/ws
# =========================
# AUTH SERVICE
# =========================
server.auth=${SERVER_AUTH}
server.auth.user=${AUTH_USER}
server.auth.pass=${AUTH_PASS}

